---
title: Practica 3. Tiempo en geomorfología
author: <b>José-Ramón Martínez-Batlle</b> (jmartinez19@uasd.edu.do) <br> Facultad de Ciencias, Universidad Autónoma de Santo Domingo (UASD) <br> Santo Domingo, República Dominicana
bibliography: references.bib
csl: apa-es.csl
lang: es
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- Este archivo se genera a partir de otro del mismo nombre con extensión .Rmd. Por favor, edita ese archivo. -->

> Fecha de entrega: en aula


```{r, echo=F, include=F}
set.seed(99)
terminales_1d <- 0:99
terminales_2d <- ifelse(nchar(terminales_1d)==1, paste0(0, terminales_1d), terminales_1d)
`Porcentaje remanente` <- sample(terminales_1d, replace = F)
```

# Practica 3. Tiempo en geomorfología

## Objetivo

Proponer una cronología para el relieve a partir de la información extraída desde el mapa geológico, interpretando la evolución geomorfológica más probable según las secuencias estratigráficas visibles en el área seleccionada, en el entorno y en el contexto regional.

## EJERCICIO único: Datación relativa de relieves

Usa [este mapa geológico](data/practica-03/practica-03.jpg), localiza tu cuadro de 5x5 km asignado (debe coincidir con los dos últimos dígitos de tu matrícula). Identifica las rocas que hay dentro del cuadro, tanto su tipología, como su edad (si no logras ver las rocas o el mapa es difuso, puedes confirmar con [este](https://drive.google.com/file/d/1NKyZjxzIedFq6Lq0bx-2YrGq5PtMh_r7/view), o con [este](data/practica-03/geo250k.jpg) o con [este otro](data/practica-03/geo250k.tif)). Refresca la cronología siguiendo la tabla cronoestratigráfica internacional, usando [este enlace](data/practica-03/tabla-cronoestratigrafica-2021.pdf) o [este otro](https://stratigraphy.org/ICSchart/ChronostratChart2021-05Spanish.pdf). Redacta un párrafo que sintetice la evolución del relieve, con sus dataciones relativas debidamente identificadas.


## Criterios de evaluación y escala de valoración

| Criterio                           | Nivel 1 (En Desarrollo) | Nivel 2 (Aceptable) | Nivel 3 (Bueno) | Nivel 4 (Excelente) |
|------------------------------------|-------------------------|---------------------|-----------------|---------------------|
| **Interpretación de Mapas Geológicos** | Interpretación inadecuada o incorrecta de los mapas geológicos. | Interpretación básica de los mapas geológicos con algunos errores. | Interpretación correcta y detallada de los mapas geológicos. | Interpretación excepcionalmente precisa y completa de los mapas geológicos. |
| **Propuesta de Cronología del Relieve** | Propuesta de cronología del relieve poco clara o incoherente. | Cronología del relieve coherente pero con imprecisiones o falta de detalle. | Propuesta de cronología del relieve bien fundamentada y detallada. | Excelente y detallada propuesta de cronología del relieve con justificación sólida. |
| **Uso de Secuencias Estratigráficas** | Uso inadecuado o incorrecto de secuencias estratigráficas en la interpretación. | Uso adecuado de secuencias estratigráficas con algunos errores de interpretación. | Uso correcto y eficaz de secuencias estratigráficas en la interpretación. | Uso excepcional de secuencias estratigráficas para una interpretación detallada y completa. |
| **Contextualización Geomorfológica** | Poca o ninguna contextualización geomorfológica del área seleccionada. | Contextualización básica del área, pero falta de integración en el contexto regional. | Buena contextualización geomorfológica del área en el contexto regional. | Excelente contextualización geomorfológica, integrando completamente el área en el contexto regional. |
| **Calidad de la Redacción** | Redacción pobre con numerosos errores gramaticales y de estilo. | Redacción clara con algunos errores gramaticales y de estilo. | Redacción bien estructurada con pocos errores gramaticales. | Redacción impecable, estructurada y coherente, sin errores gramaticales. |


## Referencias
